#########################################################
#PROJETO ACESSO
#########################################################

#CRIANDO TABELAS
#CREATE TABLE IF NOT EXISTS PESSOA(
#	ID INT AUTO_INCREMENT PRIMARY KEY,
#    NOME VARCHAR(30) NOT NULL
#);

#CREATE TABLE IF NOT EXISTS TELEFONE(
#	ID INT NOT NULL,
#    NUMERO CHAR(9)NOT NULL,
#    FOREIGN KEY (ID) REFERENCES PESSOA (ID) 
#);


#TESTE: POVOANDO BANDO DE DADOS
#INSERT INTO PESSOA(NOME) VALUES ('Berg Dantas');
#INSERT INTO PESSOA(NOME) VALUES ('Juliana Schivani');
#INSERT INTO PESSOA(NOME) VALUES ('J. Carlos');
#INSERT INTO PESSOA(NOME) VALUES ('Xavier');
#INSERT INTO PESSOA(NOME) VALUES ('Eduarda');
#INSERT INTO PESSOA(NOME) VALUES ('Fernanda');
#INSERT INTO TELEFONE(ID, NUMERO) VALUES (1, '996360653');
#INSERT INTO TELEFONE(ID, NUMERO) VALUES (1, '878956235');
#INSERT INTO TELEFONE(ID, NUMERO) VALUES (2, '996360653');
#INSERT INTO TELEFONE(ID, NUMERO) VALUES (3, '875426987');
#INSERT INTO TELEFONE(ID, NUMERO) VALUES (4, '875421658');
#INSERT INTO TELEFONE(ID, NUMERO) VALUES (5, '875424578');
#INSERT INTO TELEFONE(ID, NUMERO) VALUES (6, '874214547');

#FAZENDO BUSCAS
#SELECT * FROM PESSOA;
#SELECT * FROM TELEFONE;
#SELECT NUMERO FROM TELEFONE WHERE NUMERO='996360653';
#SELECT NOME, NUMERO FROM TELEFONE, PESSOA WHERE PESSOA.ID = TELEFONE.ID;